config/routes.rb
Rails.application.routes.draw do
  	get 'welcome/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root 'welcome#index'
    resources :articles do
    	resources :comments
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	has_many :comments, dependent: :destroy
	validates :title, presence: true,
                    length: { minimum: 5 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	
	#http_basic_authenticate_with name: "Abhishek", password: "Abhishek_@bhishek", except: [:index, :show]

	def index
    	@articles = Article.all
  	end

	def show
    	@article = Article.find(params[:id])
  	end


	def new
		@article = Article.new
	end

	def edit
		@article = Article.find(params[:id])
	end

	def create
  		@article = Article.new(article_params)
  		#@article.save
  		if @article.save
  			redirect_to @article
  		else
  			render 'new'

  		end
	end

	def update
		@article = Article.find(params[:id])
		if @article.update(article_params)
			redirect_to @article
		else
			render 'edit'
		end
	end

	def destroy
		@article = Article.find(params[:id])
		@article.destroy
		redirect_to articles_path
	end
 
	private
  	def article_params
    	params.require(:article).permit(:title, :text)
  	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	http_basic_authenticate_with name: "Abhishek", password: "Abhishek_@bhishek", except: [:index, :show]
	
	def create
		@article = Article.find(params[:article_id])
		@comment = @article.comments.create(comment_params)
		redirect_to article_path(@article)
	end

	def destroy
		@article = Article.find(params[:article_id])
		@comment = @article.comments.find(params[:id])
		@comment.destroy
		redirect_to article_path(@article)
	end

	private

	def comment_params
		params.require(:comment).permit(:commenter, :body)
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.haml
= form_with model: @article, local: true do |form|
  - if @article.errors.any?
    #error_explanation
      %h2
        = pluralize(@article.errors.count, "error")
        prohibited
        this article from being saved:
      %ul
        - @article.errors.full_messages.each do |msg|
          %li= msg
  %p
    = form.label :title
    %br/
    = form.text_field :title
  %p
    = form.label :text
    %br/
    = form.text_area :text
  %p
    = form.submit

app/views/articles/edit.html.haml
%h1 Edit Article
= render 'form'
= link_to 'Back', articles_path

app/views/articles/index.html.haml
= link_to 'New article', new_article_path
%h1 Listing Articles
%table
  %tr
    %th Id
    %th Title
    %th Text
    %th Link
  - @articles.each do |article|
    %tr
      %td= article.id
      %td= article.title
      %td= article.text
      %td= link_to 'Show', article_path(article)
      %td= link_to 'Edit', edit_article_path(article)
      %td= link_to 'Delete', article_path(article), method: :delete, data: {confirm: 'Are you sure'}

= form_with scope: :article, url: articles_path, local: true do |form|
  \...
= link_to 'Back', welcome_index_path

app/views/articles/new.html.haml
%h1 New Article
= render 'form'
= link_to 'Back', articles_path

app/views/articles/show.html.haml
%p
  %strong Title:
  = @article.title
%p
  %strong Text:
  = @article.text

%h2 Comments
= render @article.comments

%h2 Add a comment:
= render 'comments/form'

= link_to 'Edit', edit_article_path(@article)
|
= link_to 'Back', articles_path

app/views/comments/_comment.html.haml
%p
  %strong Commenter:
  = comment.commenter
%p
  %strong Comment:
  = comment.body

= link_to 'Destroy Comment', [comment.article, comment], method: :delete, data: {confirm: "Are you sure?"}

app/views/comments/_form.html.haml
%h2 Add a comment:
= form_with(model: [ @article, @article.comments.build ], local: true) do |form|
  %p
    = form.label :commenter
    %br/
    = form.text_field :commenter
  %p
    = form.label :body
    %br/
    = form.text_area :body
  %p
    = form.submit

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.haml
%h1 Hello, Rails!
= link_to 'My Blog', controller: 'articles'